name: Release

on:
  release:
    types: [created]
    secrets:
      VAULT_ADDR:
        description: "Vault address"
        required: true
      VAULT_NAMESPACE:
        description: "Vault namespace"
        required: true
      VAULT_ROLE_ID:
        description: "Vault role id"
        required: true
      VAULT_ROLE_SECRET:
        description: "Vault secret id"
        required: true

jobs:
  detect-functions:
    name: Detect functions directories
    uses: ./.github/workflows/detect-functions.yml
    with:
      runs-on-runner: ubuntu-latest
      jobs-timeout-minutes: 20
      working-directory: functions
  package:
    name: Package functions
    uses: ./.github/workflows/package.yml
    needs: detect-functions
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        function: ${{ fromJSON(needs.detect-functions.outputs.all-functions) }}
      max-parallel: 1
    with:
      jobs-timeout-minutes: 30
      runs-on-runner: ubuntu-latest
      function: ${{ matrix.function }}
      working-directory: functions
