name: Release

on:
  push:
  release:
    types: [created]
    secrets:
      VAULT_ADDR:
        description: "Vault address"
        required: true
      VAULT_NAMESPACE:
        description: "Vault namespace"
        required: true
      VAULT_ROLE_ID:
        description: "Vault role id"
        required: true
      VAULT_ROLE_SECRET:
        description: "Vault secret id"
        required: true
    
env:
  FUNCTIONS_DIR: functions

jobs:
  working-directories:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Detect working directories
    outputs:
      working-dir: ${{ steps.detect.outputs.working_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Detect functions directories
        id: detect
        run: |
          working_dir=$(find $FUNCTIONS_DIR -maxdepth 1 -mindepth 1 -type d -print | cut -d'/' -f2 | jq -R . | jq -s . )
          echo working_dir=$working_dir >> $GITHUB_OUTPUT

  package:
    name: Package
    uses: ./.github/workflows/package.yml
    needs: working-directories
    secrets: inherit
    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.working-directories.outputs.working-dir) }}
      max-parallel: 1
    with:
      functions-dir: ${{ env.FUNCTIONS_DIR }}
      jobs-timeout-minutes: 30
      runs-on-runner: ubuntu-latest

  