name: Release

on:
  push:
  release:
    types: [created]
    secrets:
      VAULT_ADDR:
        description: "Vault address"
        required: true
      VAULT_NAMESPACE:
        description: "Vault namespace"
        required: true
      VAULT_ROLE_ID:
        description: "Vault role id"
        required: true
      VAULT_ROLE_SECRET:
        description: "Vault secret id"
        required: true

jobs:
  working-directories:
    name: Working directories
    uses: ./.github/workflows/work-directory.yml
    with:
      runs-on-runner: ubuntu-latest
      jobs-timeout-minutes: 20
      functions-dir: functions
  package:
    name: Package
    uses: ./.github/workflows/package.yml
    needs: working-directories
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.working-directories.outputs.all-functions) }}
      max-parallel: 1
    with:
      jobs-timeout-minutes: 30
      runs-on-runner: ubuntu-latest
      working-directory: ${{ matrix.working-directory }}
      functions-dir: functions
