name: Work directory

on:
  workflow_call:
    outputs:
      all-functions: ${{ steps.work-directory.outputs.all-functions }}
      changes: ${{ steps.work-directory.outputs.changes }}
    inputs:
      runs-on-runner:
        description: "Runner where the pipeline will be executed"
        required: false
        type: string
        default: ubuntu-latest
      jobs-timeout-minutes:
        description: "The maximum number of minutes to let a job run before GitHub automatically cancels it"
        required: false
        type: number
        default: 20
      functions-dir:
        description: "Directory where the functions are located"
        required: false
        type: string
        default: functions

jobs:
  work-directory:
    name: Detect working directories
    runs-on: ${{ inputs.runs-on-runner }}
    timeout-minutes: ${{ inputs.jobs-timeout-minutes }}
    outputs:
      all-functions: ${{ steps.detect.outputs.working-dirs }}
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Detect functions directories
        id: detect
        run: |
          filter=""
          work_dirs="["

          for dir in $(find functions -mindepth 1 -maxdepth 1 -type d); do
            dir=${dir#functions/}
            
            filter+="\"$dir\":\"functions/$dir/**\","
            work_dirs+="\"$dir\","
          done

          filter="{${filter%,}}"
          work_dirs="${work_dirs%,}]"

          echo filter=$filter >> $GITHUB_OUTPUT
          echo working-dirs=$work_dirs >> $GITHUB_OUTPUT

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: ${{ steps.detect.outputs.filter }}
          base: main
